[pytest]
filterwarnings =
    ignore:Please use `import python_multipart` instead\.:PendingDeprecationWarning
    ignore:jsonschema\.RefResolver is deprecated.*:DeprecationWarning
markers =
    e2e: end-to-end tests
